apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: YOUR_ECR_REPO_URL/ecommerce-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "jdbc:postgresql://ecommercedb.c12345678901.us-east-1.rds.amazonaws.com:5432/ecommercedb"


